### ISSUE TITLE
编译界面中，一些软件的版本是否应该更新了？

### ISSUE THREAD

**Issue by tasty0tomato** [Qv2ray/qv2ray.github.io#104]
比如qt版本，目前支持的版本为5.15

**Comment by DuckSoft** [comment]
“编译界面”是指的哪里的界面？更新是哪里呢？

**Comment by tasty0tomato** [comment]
> “编译界面”是指的哪里的界面？更新是哪里呢？

您好，[编译界面](https://qv2ray.net/hacking/manuallybuild.html)
更新指的是，例如qt的版本，建议的版本是5.13 5.14，但是官网上似乎已经不支持以上两个版本了。

**Comment by DuckSoft** [comment]
可以，欢迎 PR～

**Comment by 2014CAIS01** [comment]
这边的英文版已经在 44cfca 中更新，中文版本似乎没有同步。

**Comment by tasty0tomato** [comment]
怎么使用[CMake Argument Reference](https://qv2ray.net/hacking/cmake-argument.html#cmake-argument-reference)，
这是我对于_CMake_的理解，可能有误？
![mintty_kpLtew2Ee2](https://user-images.githubusercontent.com/48764449/111278916-149c1100-8675-11eb-90a0-de4ca8dce407.png)

**Comment by 12101111** [comment]
定义bool变量`VAR=ON`的语法是`-DVAR=ON`

**Comment by tasty0tomato** [comment]
另外提供一个发现，目前的文档中MSVC的版本是VS2019，qt的版本是大于5.11。
但是QT5.12（似乎）并没有提供VS2019的包，似乎只提供VS2015与VS2017。
由于我一般不用QT，所以对这个到底有没有影响也无法确定。

**Comment by 12101111** [comment]
最近几年的MSVC是向前兼容的吧:https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160

**Comment by tasty0tomato** [comment]
> 
> 
> 最近几年的MSVC是向前兼容的吧:https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160

那这波我sb了，难受

**Comment by tasty0tomato** [comment]
因为昨天用msys2没弄成功，所以今天试了一下MSVC，然后包用的vspkg，但是似乎除了一些问题。
![2021-03-17 12_21_32-Windows PowerShell](https://user-images.githubusercontent.com/48764449/111414741-744cf780-871b-11eb-9dd2-f56efe0ce906.png)
我确定我肯定是安装了那几个包了

**Comment by tasty0tomato** [comment]
> 因为昨天用msys2没弄成功，所以今天试了一下MSVC，然后包用的vspkg，但是似乎除了一些问题。
> ![2021-03-17 12_21_32-Windows PowerShell](https://user-images.githubusercontent.com/48764449/111414741-744cf780-871b-11eb-9dd2-f56efe0ce906.png)
> 我确定我肯定是安装了那几个包了

这个问题解决了，因为vspkg默认安装的是X86的，改成X64即可，但出现了新问题，在编译步骤，出现报错了。（我编译的版本是2.6.3），导致安装步骤失败。
![2021-03-17 14_20_56-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/48764449/111424117-458b4d00-872c-11eb-935e-2a39e1b02948.png)

**Comment by tasty0tomato** [comment]
我等新的稳定版本出来再尝试吧，感觉2.6.3已经比较老了，跟文档不符合了
