### ISSUE TITLE
文档中 :::tip 部分的 markdown 链接并不会被正确渲染

### ISSUE THREAD

**Issue by LuXts** [Qv2ray/qv2ray.github.io#113]
翻译中看到的。
![image_2021-03-20_12-40-48](https://user-images.githubusercontent.com/49251098/111859182-ede22100-8979-11eb-9ee1-07f9affc34f8.png)

**Comment by cubercsl** [comment]
我们的文档进行了一次重构，翻译在 https://translate.qv2ray.net 进行中，目前仍然有部分内容未完成翻译或站内链接错误等问题，有能力请尽量参考英文文档。同时欢迎贡献文档的中文翻译~

**Comment by U-v-U** [comment]
Fixed, closing!
