### ISSUE TITLE
也许是 crowdin feature 造成的，每两句话之间存在空格。

### ISSUE THREAD

**Issue by sixg0000d** [Qv2ray/qv2ray.github.io#151]
简单搜索了下，数量有点大，且大部分都是该情况

![Screenshot_20210509_223549](https://user-images.githubusercontent.com/17105863/117576052-f0116200-b116-11eb-8ad3-c49c6fbcd31a.png)

所以先记在这，慢慢来吧。

**Comment by DuckSoft** [comment]
辛苦。
