### ISSUE TITLE
Qv2ray.v2.7.0-pre1.linux-x64.AppImage GUI出现撕裂

### ISSUE THREAD

**Issue by Corybyte** [Qv2ray/qv2ray.github.io#166]
Qv2ray.v2.7.0-pre1.linux-x64.AppImage GUI出现撕裂

Ubuntu 20.04 
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
MemTotal:       16360216 kB
NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev  #a1)

**Comment by 8MiYile** [comment]
去错地方了老哥 你应该去主程序的仓库而不是网站的仓库
