### ISSUE TITLE
new plugin: QvPlugin-Trojan-Go

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/qv2ray.github.io#27]
Updates Required:

- [x] https://qv2ray.github.io/en/plugins/usage.html#what-is-a-plugin
- [x] https://qv2ray.github.io/plugins/usage.html#%E4%BD%95%E4%B8%BA%E6%8F%92%E4%BB%B6

**Comment by U-v-U** [comment]
Usage page updated by @tzwjkl in https://github.com/Qv2ray/qv2ray.github.io/commit/b71b2f34543f44633c0afa954e5d2c27229a2ae4

**Comment by U-v-U** [comment]
English usage page updated by @tzwjkl in https://github.com/Qv2ray/qv2ray.github.io/commit/06bf3f8795bb065fc20879688584552958a3b610

**Comment by U-v-U** [comment]
Thanks @tzwjkl
