### ISSUE TITLE
建议增设通过v2ray官网install脚本目录提示

### ISSUE THREAD

**Issue by CHN-STUDENT** [Qv2ray/qv2ray.github.io#42]
RT，
建议增设通过v2ray官网的`go.sh`脚本安装v2ray的目录路径。
> 见 https://www.v2ray.com/chapter_00/install.html

执行文件路径 `/usr/bin/v2ray/v2ray`
资源文件路径 `/usr/bin/v2ray/`

感谢

**Comment by Copay** [comment]
@CHN-STUDENT 什么意思

**Comment by CHN-STUDENT** [comment]
@Copay 抱歉刚不小心直接按到回车发出来了，请见我顶楼的需求，希望增设通过v2ray官方安装脚本路径提示。

**Comment by U-v-U** [comment]
根据 FHS 要求， /usr/bin 内不应包含文件夹

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s04.html

```
4.4.2. Requirements

There must be no subdirectories in /usr/bin.
```

```
/usr/bin > find -type d
./vendor_perl
./core_perl
./lou_maketable.d
./site_perl
```

或许您应该通知上游去修改

**Comment by U-v-U** [comment]
根据 FHS 要求， /usr/bin 内不应包含文件夹

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s04.html

```
4.4.2. Requirements

There must be no subdirectories in /usr/bin.
```

或许您应该通知上游去修改

**Comment by CHN-STUDENT** [comment]
@U-v-U v2 的官方 linux 安装脚本就是这样的策略，不管了，能用就行，但是还是建议在 qv2ray 文档里提及或者引用一下

**Comment by Copay** [comment]
@CHN-STUDENT 建议使用包管理器安装v2ray

**Comment by DuckSoft** [comment]
`v2ray.com` 已经弃用了，社区维护的在 `v2fly.org`。
那个脚本不是我们维护的，而且不符合 FHS 要求，我个人反对添加到 Qv2ray 文档里。

> @U-v-U v2 的官方 linux 安装脚本就是这样的策略，不管了，能用就行，但是还是建议在 qv2ray 文档里提及或者引用一下

**Comment by kslr** [comment]
现在你需要使用 https://github.com/v2fly/fhs-install-v2ray/

**Comment by DuckSoft** [comment]
https://github.com/v2ray/v2ray-core/issues/2328
https://github.com/v2fly/fhs-install-v2ray
https://www.v2fly.org/guide/install.html#linux-%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC

**Comment by CHN-STUDENT** [comment]
@DuckSoft 我个人建议是否能在文档里链接下这个安装脚本，毕竟我也是刚知道的，如果链接到文档里可能会对后来人有所帮助？

**Comment by CHN-STUDENT** [comment]
#44
