### ISSUE TITLE
TODO: 澄清有关 QvPlugin-SS 的几个问题

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/qv2ray.github.io#59]
提纲：
 - QvPlugin-SS 的用途是支持 Shadowsocks 的某些 SIP003 扩展，如 `simple-obfs`（已弃用）、`kcptun` 等；并非用来支持 Shadowsocks 协议。
 - 不装 SS 插件就用不了 Shadowsocks 的说法是错误的，因为 V2Ray 核心自带部分 Shadowsocks 功能。

**Comment by wallena3** [comment]
也许支持的扩展举例再加上
https://github.com/shadowsocks/v2ray-plugin
