### ISSUE TITLE
Instructions given on gettings-started/step3 do not match with the user interface

### ISSUE THREAD

**Issue by Gowee** [Qv2ray/qv2ray.github.io#66]
In https://github.com/Qv2ray/qv2ray.github.io/blob/source/docs/en/getting-started/step3.md, subsection "Subscription", it reads:

> 1. Click Subscriptions button in the main window.

I cannot find a button named "Subscritions" in the main window.

Qv2ray version: `qv2ray 2.6.3` [bulit by archlinuxcn](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/qv2ray/PKGBUILD)

**Comment by U-v-U** [comment]
It's been moved to "Group" option.

**Comment by Gowee** [comment]
Yes. But the change is only reflected in the Simplified Chinese documentation, where the descriptions are also slightly different from what I see:
![image](https://user-images.githubusercontent.com/8171899/95279249-ce9c7f00-0884-11eb-9914-2c1ab939cf3d.png)

> 1. 点击 分组/订阅 进入 组编辑器（订阅编辑器）。

It is called "分组" (w/o "/订阅") in my case.

> 3. 单击此处可在 订阅列表 中选择新生成的项

"组列表" in my case.

> 4. 在右侧输入您的订阅信息

Actually, it takes more steps to activate the subscriptions: switch to "订阅设置" tab and tick the "此分组是一个订阅" checkbox.

As a new user, it is fairly confusing to me. It would be great if both the zh & en documentations are updated to be consistent with the actual user interface.

**Comment by U-v-U** [comment]
Sorry about the inconvenience, it's been poorly maintained since there're few people using the Engligh version.
It'll be great if someone help to translate those pages.

**Comment by DuckSoft** [comment]
I am working on a fix now.

**Comment by DuckSoft** [comment]
This is resolved in commit 7af96039a541adef1feaf99bba30f6779363ce3d. 
Deployment may take some time, please be patient though.

**Comment by Gowee** [comment]
Thanks for your work, @U-v-U and @DuckSoft!
