### ISSUE TITLE
[question] may be an error

### ISSUE THREAD

**Issue by Freed-Wu** [Qv2ray/qv2ray.github.io#77]
in <https://qv2ray.net/en/faq/#connection-problems>

```
Approach 1: Use systemd-timesyncd, run sudo systemctl enable systemd-timesyncd --now。
```

in my gentoo OS, `systemd-timesyncd` doesn't exist. only `systemd-timesync`
exists. after `systemd-timesync` was installed, it should be `sudo systemctl enable systemd-time-wait-sync.service --now`
not `sudo systemctl enable systemd-timesyncd --now`.

i don't determine whether it is an error or an exception for my OS. i believe
the latter is more probable. if so, perhaps it should be added to the
document.

thanks for your listening.

BTW, the chinese `。` of `run sudo systemctl enable systemd-timesyncd --now。` should
be english `.`.

**Comment by U-v-U** [comment]
May not.

**Comment by U-v-U** [comment]
Maybe not.

**Comment by Freed-Wu** [comment]
wait a minute for my typing...

**Comment by Freed-Wu** [comment]
i have edited the description of the issue. sorry for my late.

**Comment by U-v-U** [comment]
So it's related to the doc?

**Comment by U-v-U** [comment]
![image](https://user-images.githubusercontent.com/59914293/101561106-ab668b00-39ff-11eb-823e-5fb4f8af49f9.png)

Seems there's no errors.
The Chinese 。 has been fixed.

**Comment by Freed-Wu** [comment]
Great! Thanks for your explanation!
